# This is a basic workflow to help you get started with Actions

name: website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: webpage

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          pwd
          ls -l
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ secrets.SSHKEY }}" > chave.pem
          chmod 600 chave.pem
          ls -l
          ssh -o StrictHostKeyChecking=no -i chave.pem gestor@98.66.211.8 "\
            sudo apt update && \
            sudo apt install -y apache2 && \
            sudo chmod -R 777 /var/www/html"
          scp -o StrictHostKeyChecking=no -i chave.pem ./index.html gestor@98.66.211.8:/var/www/html/index.html
          ls -l
